name: flutter_bluetooth_basic
description: Flutter plugin that allows to find bluetooth devices & send raw bytes data
version: 1.0.3
homepage: https://github.com/andrey-ushakov/flutter_bluetooth_basic


environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  rxdart: ^0.27.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6

  integration_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.tablemi.flutter_bluetooth_basic
        pluginClass: FlutterBluetoothBasicPlugin
      ios:
        pluginClass: FlutterBluetoothBasicPlugin